import { PhoneData } from './types';

export const flagsData: PhoneData[] = [
	{
		code: 'AC',
		name: 'AC',
		calling_code: 247,
		flag_class: 'fi fi-ac',
		flag: 'ac.svg',
	},
	{
		code: 'AD',
		name: 'Andorra',
		calling_code: 376,
		flag_class: 'fi fi-ad',
		flag: 'ad.svg',
	},
	{
		code: 'AE',
		name: 'United Arab Emirates',
		calling_code: 971,
		flag_class: 'fi fi-ae',
		flag: 'ae.svg',
	},
	{
		code: 'AF',
		name: 'Afghanistan',
		calling_code: 93,
		flag_class: 'fi fi-af',
		flag: 'af.svg',
	},
	{
		code: 'AG',
		name: 'Antigua and Barbuda',
		calling_code: 1,
		flag_class: 'fi fi-ag',
		flag: 'ag.svg',
	},
	{
		code: 'AI',
		name: 'Anguilla',
		calling_code: 1,
		flag_class: 'fi fi-ai',
		flag: 'ai.svg',
	},
	{
		code: 'AL',
		name: 'Albania',
		calling_code: 355,
		flag_class: 'fi fi-al',
		flag: 'al.svg',
	},
	{
		code: 'AM',
		name: 'Armenia',
		calling_code: 374,
		flag_class: 'fi fi-am',
		flag: 'am.svg',
	},
	{
		code: 'AO',
		name: 'Angola',
		calling_code: 244,
		flag_class: 'fi fi-ao',
		flag: 'ao.svg',
	},
	{
		code: 'AR',
		name: 'Argentina',
		calling_code: 54,
		flag_class: 'fi fi-ar',
		flag: 'ar.svg',
	},
	{
		code: 'AS',
		name: 'American Samoa',
		calling_code: 1,
		flag_class: 'fi fi-as',
		flag: 'as.svg',
	},
	{
		code: 'AT',
		name: 'Austria',
		calling_code: 43,
		flag_class: 'fi fi-at',
		flag: 'at.svg',
	},
	{
		code: 'AU',
		name: 'Australia',
		calling_code: 61,
		flag_class: 'fi fi-au',
		flag: 'au.svg',
	},
	{
		code: 'AW',
		name: 'Aruba',
		calling_code: 297,
		flag_class: 'fi fi-aw',
		flag: 'aw.svg',
	},
	{
		code: 'AX',
		name: 'Åland Islands',
		calling_code: 358,
		flag_class: 'fi fi-ax',
		flag: 'ax.svg',
	},
	{
		code: 'AZ',
		name: 'Azerbaijan',
		calling_code: 994,
		flag_class: 'fi fi-az',
		flag: 'az.svg',
	},
	{
		code: 'BA',
		name: 'Bosnia and Herzegovina',
		calling_code: 387,
		flag_class: 'fi fi-ba',
		flag: 'ba.svg',
	},
	{
		code: 'BB',
		name: 'Barbados',
		calling_code: 1,
		flag_class: 'fi fi-bb',
		flag: 'bb.svg',
	},
	{
		code: 'BD',
		name: 'Bangladesh',
		calling_code: 880,
		flag_class: 'fi fi-bd',
		flag: 'bd.svg',
	},
	{
		code: 'BE',
		name: 'Belgium',
		calling_code: 32,
		flag_class: 'fi fi-be',
		flag: 'be.svg',
	},
	{
		code: 'BF',
		name: 'Burkina Faso',
		calling_code: 226,
		flag_class: 'fi fi-bf',
		flag: 'bf.svg',
	},
	{
		code: 'BG',
		name: 'Bulgaria',
		calling_code: 359,
		flag_class: 'fi fi-bg',
		flag: 'bg.svg',
	},
	{
		code: 'BH',
		name: 'Bahrain',
		calling_code: 973,
		flag_class: 'fi fi-bh',
		flag: 'bh.svg',
	},
	{
		code: 'BI',
		name: 'Burundi',
		calling_code: 257,
		flag_class: 'fi fi-bi',
		flag: 'bi.svg',
	},
	{
		code: 'BJ',
		name: 'Benin',
		calling_code: 229,
		flag_class: 'fi fi-bj',
		flag: 'bj.svg',
	},
	{
		code: 'BL',
		name: 'Saint Barthélemy',
		calling_code: 590,
		flag_class: 'fi fi-bl',
		flag: 'bl.svg',
	},
	{
		code: 'BM',
		name: 'Bermuda',
		calling_code: 1,
		flag_class: 'fi fi-bm',
		flag: 'bm.svg',
	},
	{
		code: 'BN',
		name: 'Brunei',
		calling_code: 673,
		flag_class: 'fi fi-bn',
		flag: 'bn.svg',
	},
	{
		code: 'BO',
		name: 'Bolivia',
		calling_code: 591,
		flag_class: 'fi fi-bo',
		flag: 'bo.svg',
	},
	{
		code: 'BQ',
		name: 'Caribbean Netherlands',
		calling_code: 599,
		flag_class: 'fi fi-bq',
		flag: 'bq.svg',
	},
	{
		code: 'BR',
		name: 'Brazil',
		calling_code: 55,
		flag_class: 'fi fi-br',
		flag: 'br.svg',
	},
	{
		code: 'BS',
		name: 'Bahamas',
		calling_code: 1,
		flag_class: 'fi fi-bs',
		flag: 'bs.svg',
	},
	{
		code: 'BT',
		name: 'Bhutan',
		calling_code: 975,
		flag_class: 'fi fi-bt',
		flag: 'bt.svg',
	},
	{
		code: 'BW',
		name: 'Botswana',
		calling_code: 267,
		flag_class: 'fi fi-bw',
		flag: 'bw.svg',
	},
	{
		code: 'BY',
		name: 'Belarus',
		calling_code: 375,
		flag_class: 'fi fi-by',
		flag: 'by.svg',
	},
	{
		code: 'BZ',
		name: 'Belize',
		calling_code: 501,
		flag_class: 'fi fi-bz',
		flag: 'bz.svg',
	},
	{
		code: 'CA',
		name: 'Canada',
		calling_code: 1,
		flag_class: 'fi fi-ca',
		flag: 'ca.svg',
	},
	{
		code: 'CC',
		name: 'Cocos (Keeling) Islands',
		calling_code: 61,
		flag_class: 'fi fi-cc',
		flag: 'cc.svg',
	},
	{
		code: 'CD',
		name: 'DR Congo',
		calling_code: 243,
		flag_class: 'fi fi-cd',
		flag: 'cd.svg',
	},
	{
		code: 'CF',
		name: 'Central African Republic',
		calling_code: 236,
		flag_class: 'fi fi-cf',
		flag: 'cf.svg',
	},
	{
		code: 'CG',
		name: 'Republic of the Congo',
		calling_code: 242,
		flag_class: 'fi fi-cg',
		flag: 'cg.svg',
	},
	{
		code: 'CH',
		name: 'Switzerland',
		calling_code: 41,
		flag_class: 'fi fi-ch',
		flag: 'ch.svg',
	},
	{
		code: 'CI',
		name: 'Ivory Coast',
		calling_code: 225,
		flag_class: 'fi fi-ci',
		flag: 'ci.svg',
	},
	{
		code: 'CK',
		name: 'Cook Islands',
		calling_code: 682,
		flag_class: 'fi fi-ck',
		flag: 'ck.svg',
	},
	{
		code: 'CL',
		name: 'Chile',
		calling_code: 56,
		flag_class: 'fi fi-cl',
		flag: 'cl.svg',
	},
	{
		code: 'CM',
		name: 'Cameroon',
		calling_code: 237,
		flag_class: 'fi fi-cm',
		flag: 'cm.svg',
	},
	{
		code: 'CN',
		name: 'China',
		calling_code: 86,
		flag_class: 'fi fi-cn',
		flag: 'cn.svg',
	},
	{
		code: 'CO',
		name: 'Colombia',
		calling_code: 57,
		flag_class: 'fi fi-co',
		flag: 'co.svg',
	},
	{
		code: 'CR',
		name: 'Costa Rica',
		calling_code: 506,
		flag_class: 'fi fi-cr',
		flag: 'cr.svg',
	},
	{
		code: 'CU',
		name: 'Cuba',
		calling_code: 53,
		flag_class: 'fi fi-cu',
		flag: 'cu.svg',
	},
	{
		code: 'CV',
		name: 'Cape Verde',
		calling_code: 238,
		flag_class: 'fi fi-cv',
		flag: 'cv.svg',
	},
	{
		code: 'CW',
		name: 'Curaçao',
		calling_code: 599,
		flag_class: 'fi fi-cw',
		flag: 'cw.svg',
	},
	{
		code: 'CX',
		name: 'Christmas Island',
		calling_code: 61,
		flag_class: 'fi fi-cx',
		flag: 'cx.svg',
	},
	{
		code: 'CY',
		name: 'Cyprus',
		calling_code: 357,
		flag_class: 'fi fi-cy',
		flag: 'cy.svg',
	},
	{
		code: 'CZ',
		name: 'Czechia',
		calling_code: 420,
		flag_class: 'fi fi-cz',
		flag: 'cz.svg',
	},
	{
		code: 'DE',
		name: 'Germany',
		calling_code: 49,
		flag_class: 'fi fi-de',
		flag: 'de.svg',
	},
	{
		code: 'DJ',
		name: 'Djibouti',
		calling_code: 253,
		flag_class: 'fi fi-dj',
		flag: 'dj.svg',
	},
	{
		code: 'DK',
		name: 'Denmark',
		calling_code: 45,
		flag_class: 'fi fi-dk',
		flag: 'dk.svg',
	},
	{
		code: 'DM',
		name: 'Dominica',
		calling_code: 1,
		flag_class: 'fi fi-dm',
		flag: 'dm.svg',
	},
	{
		code: 'DO',
		name: 'Dominican Republic',
		calling_code: 1,
		flag_class: 'fi fi-do',
		flag: 'do.svg',
	},
	{
		code: 'DZ',
		name: 'Algeria',
		calling_code: 213,
		flag_class: 'fi fi-dz',
		flag: 'dz.svg',
	},
	{
		code: 'EC',
		name: 'Ecuador',
		calling_code: 593,
		flag_class: 'fi fi-ec',
		flag: 'ec.svg',
	},
	{
		code: 'EE',
		name: 'Estonia',
		calling_code: 372,
		flag_class: 'fi fi-ee',
		flag: 'ee.svg',
	},
	{
		code: 'EG',
		name: 'Egypt',
		calling_code: 20,
		flag_class: 'fi fi-eg',
		flag: 'eg.svg',
	},
	{
		code: 'EH',
		name: 'Western Sahara',
		calling_code: 212,
		flag_class: 'fi fi-eh',
		flag: 'eh.svg',
	},
	{
		code: 'ER',
		name: 'Eritrea',
		calling_code: 291,
		flag_class: 'fi fi-er',
		flag: 'er.svg',
	},
	{
		code: 'ES',
		name: 'Spain',
		calling_code: 34,
		flag_class: 'fi fi-es',
		flag: 'es.svg',
	},
	{
		code: 'ET',
		name: 'Ethiopia',
		calling_code: 251,
		flag_class: 'fi fi-et',
		flag: 'et.svg',
	},
	{
		code: 'FI',
		name: 'Finland',
		calling_code: 358,
		flag_class: 'fi fi-fi',
		flag: 'fi.svg',
	},
	{
		code: 'FJ',
		name: 'Fiji',
		calling_code: 679,
		flag_class: 'fi fi-fj',
		flag: 'fj.svg',
	},
	{
		code: 'FK',
		name: 'Falkland Islands',
		calling_code: 500,
		flag_class: 'fi fi-fk',
		flag: 'fk.svg',
	},
	{
		code: 'FM',
		name: 'Micronesia',
		calling_code: 691,
		flag_class: 'fi fi-fm',
		flag: 'fm.svg',
	},
	{
		code: 'FO',
		name: 'Faroe Islands',
		calling_code: 298,
		flag_class: 'fi fi-fo',
		flag: 'fo.svg',
	},
	{
		code: 'FR',
		name: 'France',
		calling_code: 33,
		flag_class: 'fi fi-fr',
		flag: 'fr.svg',
	},
	{
		code: 'GA',
		name: 'Gabon',
		calling_code: 241,
		flag_class: 'fi fi-ga',
		flag: 'ga.svg',
	},
	{
		code: 'GB',
		name: 'United Kingdom',
		calling_code: 44,
		flag_class: 'fi fi-gb',
		flag: 'gb.svg',
	},
	{
		code: 'GD',
		name: 'Grenada',
		calling_code: 1,
		flag_class: 'fi fi-gd',
		flag: 'gd.svg',
	},
	{
		code: 'GE',
		name: 'Georgia',
		calling_code: 995,
		flag_class: 'fi fi-ge',
		flag: 'ge.svg',
	},
	{
		code: 'GF',
		name: 'French Guiana',
		calling_code: 594,
		flag_class: 'fi fi-gf',
		flag: 'gf.svg',
	},
	{
		code: 'GG',
		name: 'Guernsey',
		calling_code: 44,
		flag_class: 'fi fi-gg',
		flag: 'gg.svg',
	},
	{
		code: 'GH',
		name: 'Ghana',
		calling_code: 233,
		flag_class: 'fi fi-gh',
		flag: 'gh.svg',
	},
	{
		code: 'GI',
		name: 'Gibraltar',
		calling_code: 350,
		flag_class: 'fi fi-gi',
		flag: 'gi.svg',
	},
	{
		code: 'GL',
		name: 'Greenland',
		calling_code: 299,
		flag_class: 'fi fi-gl',
		flag: 'gl.svg',
	},
	{
		code: 'GM',
		name: 'Gambia',
		calling_code: 220,
		flag_class: 'fi fi-gm',
		flag: 'gm.svg',
	},
	{
		code: 'GN',
		name: 'Guinea',
		calling_code: 224,
		flag_class: 'fi fi-gn',
		flag: 'gn.svg',
	},
	{
		code: 'GP',
		name: 'Guadeloupe',
		calling_code: 590,
		flag_class: 'fi fi-gp',
		flag: 'gp.svg',
	},
	{
		code: 'GQ',
		name: 'Equatorial Guinea',
		calling_code: 240,
		flag_class: 'fi fi-gq',
		flag: 'gq.svg',
	},
	{
		code: 'GR',
		name: 'Greece',
		calling_code: 30,
		flag_class: 'fi fi-gr',
		flag: 'gr.svg',
	},
	{
		code: 'GT',
		name: 'Guatemala',
		calling_code: 502,
		flag_class: 'fi fi-gt',
		flag: 'gt.svg',
	},
	{
		code: 'GU',
		name: 'Guam',
		calling_code: 1,
		flag_class: 'fi fi-gu',
		flag: 'gu.svg',
	},
	{
		code: 'GW',
		name: 'Guinea-Bissau',
		calling_code: 245,
		flag_class: 'fi fi-gw',
		flag: 'gw.svg',
	},
	{
		code: 'GY',
		name: 'Guyana',
		calling_code: 592,
		flag_class: 'fi fi-gy',
		flag: 'gy.svg',
	},
	{
		code: 'HK',
		name: 'Hong Kong',
		calling_code: 852,
		flag_class: 'fi fi-hk',
		flag: 'hk.svg',
	},
	{
		code: 'HN',
		name: 'Honduras',
		calling_code: 504,
		flag_class: 'fi fi-hn',
		flag: 'hn.svg',
	},
	{
		code: 'HR',
		name: 'Croatia',
		calling_code: 385,
		flag_class: 'fi fi-hr',
		flag: 'hr.svg',
	},
	{
		code: 'HT',
		name: 'Haiti',
		calling_code: 509,
		flag_class: 'fi fi-ht',
		flag: 'ht.svg',
	},
	{
		code: 'HU',
		name: 'Hungary',
		calling_code: 36,
		flag_class: 'fi fi-hu',
		flag: 'hu.svg',
	},
	{
		code: 'ID',
		name: 'Indonesia',
		calling_code: 62,
		flag_class: 'fi fi-id',
		flag: 'id.svg',
	},
	{
		code: 'IE',
		name: 'Ireland',
		calling_code: 353,
		flag_class: 'fi fi-ie',
		flag: 'ie.svg',
	},
	{
		code: 'IL',
		name: 'Israel',
		calling_code: 972,
		flag_class: 'fi fi-il',
		flag: 'il.svg',
	},
	{
		code: 'IM',
		name: 'Isle of Man',
		calling_code: 44,
		flag_class: 'fi fi-im',
		flag: 'im.svg',
	},
	{
		code: 'IN',
		name: 'India',
		calling_code: 91,
		flag_class: 'fi fi-in',
		flag: 'in.svg',
	},
	{
		code: 'IO',
		name: 'British Indian Ocean Territory',
		calling_code: 246,
		flag_class: 'fi fi-io',
		flag: 'io.svg',
	},
	{
		code: 'IQ',
		name: 'Iraq',
		calling_code: 964,
		flag_class: 'fi fi-iq',
		flag: 'iq.svg',
	},
	{
		code: 'IR',
		name: 'Iran',
		calling_code: 98,
		flag_class: 'fi fi-ir',
		flag: 'ir.svg',
	},
	{
		code: 'IS',
		name: 'Iceland',
		calling_code: 354,
		flag_class: 'fi fi-is',
		flag: 'is.svg',
	},
	{
		code: 'IT',
		name: 'Italy',
		calling_code: 39,
		flag_class: 'fi fi-it',
		flag: 'it.svg',
	},
	{
		code: 'JE',
		name: 'Jersey',
		calling_code: 44,
		flag_class: 'fi fi-je',
		flag: 'je.svg',
	},
	{
		code: 'JM',
		name: 'Jamaica',
		calling_code: 1,
		flag_class: 'fi fi-jm',
		flag: 'jm.svg',
	},
	{
		code: 'JO',
		name: 'Jordan',
		calling_code: 962,
		flag_class: 'fi fi-jo',
		flag: 'jo.svg',
	},
	{
		code: 'JP',
		name: 'Japan',
		calling_code: 81,
		flag_class: 'fi fi-jp',
		flag: 'jp.svg',
	},
	{
		code: 'KE',
		name: 'Kenya',
		calling_code: 254,
		flag_class: 'fi fi-ke',
		flag: 'ke.svg',
	},
	{
		code: 'KG',
		name: 'Kyrgyzstan',
		calling_code: 996,
		flag_class: 'fi fi-kg',
		flag: 'kg.svg',
	},
	{
		code: 'KH',
		name: 'Cambodia',
		calling_code: 855,
		flag_class: 'fi fi-kh',
		flag: 'kh.svg',
	},
	{
		code: 'KI',
		name: 'Kiribati',
		calling_code: 686,
		flag_class: 'fi fi-ki',
		flag: 'ki.svg',
	},
	{
		code: 'KM',
		name: 'Comoros',
		calling_code: 269,
		flag_class: 'fi fi-km',
		flag: 'km.svg',
	},
	{
		code: 'KN',
		name: 'Saint Kitts and Nevis',
		calling_code: 1,
		flag_class: 'fi fi-kn',
		flag: 'kn.svg',
	},
	{
		code: 'KP',
		name: 'North Korea',
		calling_code: 850,
		flag_class: 'fi fi-kp',
		flag: 'kp.svg',
	},
	{
		code: 'KR',
		name: 'South Korea',
		calling_code: 82,
		flag_class: 'fi fi-kr',
		flag: 'kr.svg',
	},
	{
		code: 'KW',
		name: 'Kuwait',
		calling_code: 965,
		flag_class: 'fi fi-kw',
		flag: 'kw.svg',
	},
	{
		code: 'KY',
		name: 'Cayman Islands',
		calling_code: 1,
		flag_class: 'fi fi-ky',
		flag: 'ky.svg',
	},
	{
		code: 'KZ',
		name: 'Kazakhstan',
		calling_code: 7,
		flag_class: 'fi fi-kz',
		flag: 'kz.svg',
	},
	{
		code: 'LA',
		name: 'Laos',
		calling_code: 856,
		flag_class: 'fi fi-la',
		flag: 'la.svg',
	},
	{
		code: 'LB',
		name: 'Lebanon',
		calling_code: 961,
		flag_class: 'fi fi-lb',
		flag: 'lb.svg',
	},
	{
		code: 'LC',
		name: 'Saint Lucia',
		calling_code: 1,
		flag_class: 'fi fi-lc',
		flag: 'lc.svg',
	},
	{
		code: 'LI',
		name: 'Liechtenstein',
		calling_code: 423,
		flag_class: 'fi fi-li',
		flag: 'li.svg',
	},
	{
		code: 'LK',
		name: 'Sri Lanka',
		calling_code: 94,
		flag_class: 'fi fi-lk',
		flag: 'lk.svg',
	},
	{
		code: 'LR',
		name: 'Liberia',
		calling_code: 231,
		flag_class: 'fi fi-lr',
		flag: 'lr.svg',
	},
	{
		code: 'LS',
		name: 'Lesotho',
		calling_code: 266,
		flag_class: 'fi fi-ls',
		flag: 'ls.svg',
	},
	{
		code: 'LT',
		name: 'Lithuania',
		calling_code: 370,
		flag_class: 'fi fi-lt',
		flag: 'lt.svg',
	},
	{
		code: 'LU',
		name: 'Luxembourg',
		calling_code: 352,
		flag_class: 'fi fi-lu',
		flag: 'lu.svg',
	},
	{
		code: 'LV',
		name: 'Latvia',
		calling_code: 371,
		flag_class: 'fi fi-lv',
		flag: 'lv.svg',
	},
	{
		code: 'LY',
		name: 'Libya',
		calling_code: 218,
		flag_class: 'fi fi-ly',
		flag: 'ly.svg',
	},
	{
		code: 'MA',
		name: 'Morocco',
		calling_code: 212,
		flag_class: 'fi fi-ma',
		flag: 'ma.svg',
	},
	{
		code: 'MC',
		name: 'Monaco',
		calling_code: 377,
		flag_class: 'fi fi-mc',
		flag: 'mc.svg',
	},
	{
		code: 'MD',
		name: 'Moldova',
		calling_code: 373,
		flag_class: 'fi fi-md',
		flag: 'md.svg',
	},
	{
		code: 'ME',
		name: 'Montenegro',
		calling_code: 382,
		flag_class: 'fi fi-me',
		flag: 'me.svg',
	},
	{
		code: 'MF',
		name: 'Saint Martin',
		calling_code: 590,
		flag_class: 'fi fi-mf',
		flag: 'mf.svg',
	},
	{
		code: 'MG',
		name: 'Madagascar',
		calling_code: 261,
		flag_class: 'fi fi-mg',
		flag: 'mg.svg',
	},
	{
		code: 'MH',
		name: 'Marshall Islands',
		calling_code: 692,
		flag_class: 'fi fi-mh',
		flag: 'mh.svg',
	},
	{
		code: 'MK',
		name: 'North Macedonia',
		calling_code: 389,
		flag_class: 'fi fi-mk',
		flag: 'mk.svg',
	},
	{
		code: 'ML',
		name: 'Mali',
		calling_code: 223,
		flag_class: 'fi fi-ml',
		flag: 'ml.svg',
	},
	{
		code: 'MM',
		name: 'Myanmar',
		calling_code: 95,
		flag_class: 'fi fi-mm',
		flag: 'mm.svg',
	},
	{
		code: 'MN',
		name: 'Mongolia',
		calling_code: 976,
		flag_class: 'fi fi-mn',
		flag: 'mn.svg',
	},
	{
		code: 'MO',
		name: 'Macau',
		calling_code: 853,
		flag_class: 'fi fi-mo',
		flag: 'mo.svg',
	},
	{
		code: 'MP',
		name: 'Northern Mariana Islands',
		calling_code: 1,
		flag_class: 'fi fi-mp',
		flag: 'mp.svg',
	},
	{
		code: 'MQ',
		name: 'Martinique',
		calling_code: 596,
		flag_class: 'fi fi-mq',
		flag: 'mq.svg',
	},
	{
		code: 'MR',
		name: 'Mauritania',
		calling_code: 222,
		flag_class: 'fi fi-mr',
		flag: 'mr.svg',
	},
	{
		code: 'MS',
		name: 'Montserrat',
		calling_code: 1,
		flag_class: 'fi fi-ms',
		flag: 'ms.svg',
	},
	{
		code: 'MT',
		name: 'Malta',
		calling_code: 356,
		flag_class: 'fi fi-mt',
		flag: 'mt.svg',
	},
	{
		code: 'MU',
		name: 'Mauritius',
		calling_code: 230,
		flag_class: 'fi fi-mu',
		flag: 'mu.svg',
	},
	{
		code: 'MV',
		name: 'Maldives',
		calling_code: 960,
		flag_class: 'fi fi-mv',
		flag: 'mv.svg',
	},
	{
		code: 'MW',
		name: 'Malawi',
		calling_code: 265,
		flag_class: 'fi fi-mw',
		flag: 'mw.svg',
	},
	{
		code: 'MX',
		name: 'Mexico',
		calling_code: 52,
		flag_class: 'fi fi-mx',
		flag: 'mx.svg',
	},
	{
		code: 'MY',
		name: 'Malaysia',
		calling_code: 60,
		flag_class: 'fi fi-my',
		flag: 'my.svg',
	},
	{
		code: 'MZ',
		name: 'Mozambique',
		calling_code: 258,
		flag_class: 'fi fi-mz',
		flag: 'mz.svg',
	},
	{
		code: 'NA',
		name: 'Namibia',
		calling_code: 264,
		flag_class: 'fi fi-na',
		flag: 'na.svg',
	},
	{
		code: 'NC',
		name: 'New Caledonia',
		calling_code: 687,
		flag_class: 'fi fi-nc',
		flag: 'nc.svg',
	},
	{
		code: 'NE',
		name: 'Niger',
		calling_code: 227,
		flag_class: 'fi fi-ne',
		flag: 'ne.svg',
	},
	{
		code: 'NF',
		name: 'Norfolk Island',
		calling_code: 672,
		flag_class: 'fi fi-nf',
		flag: 'nf.svg',
	},
	{
		code: 'NG',
		name: 'Nigeria',
		calling_code: 234,
		flag_class: 'fi fi-ng',
		flag: 'ng.svg',
	},
	{
		code: 'NI',
		name: 'Nicaragua',
		calling_code: 505,
		flag_class: 'fi fi-ni',
		flag: 'ni.svg',
	},
	{
		code: 'NL',
		name: 'Netherlands',
		calling_code: 31,
		flag_class: 'fi fi-nl',
		flag: 'nl.svg',
	},
	{
		code: 'NO',
		name: 'Norway',
		calling_code: 47,
		flag_class: 'fi fi-no',
		flag: 'no.svg',
	},
	{
		code: 'NP',
		name: 'Nepal',
		calling_code: 977,
		flag_class: 'fi fi-np',
		flag: 'np.svg',
	},
	{
		code: 'NR',
		name: 'Nauru',
		calling_code: 674,
		flag_class: 'fi fi-nr',
		flag: 'nr.svg',
	},
	{
		code: 'NU',
		name: 'Niue',
		calling_code: 683,
		flag_class: 'fi fi-nu',
		flag: 'nu.svg',
	},
	{
		code: 'NZ',
		name: 'New Zealand',
		calling_code: 64,
		flag_class: 'fi fi-nz',
		flag: 'nz.svg',
	},
	{
		code: 'OM',
		name: 'Oman',
		calling_code: 968,
		flag_class: 'fi fi-om',
		flag: 'om.svg',
	},
	{
		code: 'PA',
		name: 'Panama',
		calling_code: 507,
		flag_class: 'fi fi-pa',
		flag: 'pa.svg',
	},
	{
		code: 'PE',
		name: 'Peru',
		calling_code: 51,
		flag_class: 'fi fi-pe',
		flag: 'pe.svg',
	},
	{
		code: 'PF',
		name: 'French Polynesia',
		calling_code: 689,
		flag_class: 'fi fi-pf',
		flag: 'pf.svg',
	},
	{
		code: 'PG',
		name: 'Papua New Guinea',
		calling_code: 675,
		flag_class: 'fi fi-pg',
		flag: 'pg.svg',
	},
	{
		code: 'PH',
		name: 'Philippines',
		calling_code: 63,
		flag_class: 'fi fi-ph',
		flag: 'ph.svg',
	},
	{
		code: 'PK',
		name: 'Pakistan',
		calling_code: 92,
		flag_class: 'fi fi-pk',
		flag: 'pk.svg',
	},
	{
		code: 'PL',
		name: 'Poland',
		calling_code: 48,
		flag_class: 'fi fi-pl',
		flag: 'pl.svg',
	},
	{
		code: 'PM',
		name: 'Saint Pierre and Miquelon',
		calling_code: 508,
		flag_class: 'fi fi-pm',
		flag: 'pm.svg',
	},
	{
		code: 'PR',
		name: 'Puerto Rico',
		calling_code: 1,
		flag_class: 'fi fi-pr',
		flag: 'pr.svg',
	},
	{
		code: 'PS',
		name: 'Palestine',
		calling_code: 970,
		flag_class: 'fi fi-ps',
		flag: 'ps.svg',
	},
	{
		code: 'PT',
		name: 'Portugal',
		calling_code: 351,
		flag_class: 'fi fi-pt',
		flag: 'pt.svg',
	},
	{
		code: 'PW',
		name: 'Palau',
		calling_code: 680,
		flag_class: 'fi fi-pw',
		flag: 'pw.svg',
	},
	{
		code: 'PY',
		name: 'Paraguay',
		calling_code: 595,
		flag_class: 'fi fi-py',
		flag: 'py.svg',
	},
	{
		code: 'QA',
		name: 'Qatar',
		calling_code: 974,
		flag_class: 'fi fi-qa',
		flag: 'qa.svg',
	},
	{
		code: 'RE',
		name: 'Réunion',
		calling_code: 262,
		flag_class: 'fi fi-re',
		flag: 're.svg',
	},
	{
		code: 'RO',
		name: 'Romania',
		calling_code: 40,
		flag_class: 'fi fi-ro',
		flag: 'ro.svg',
	},
	{
		code: 'RS',
		name: 'Serbia',
		calling_code: 381,
		flag_class: 'fi fi-rs',
		flag: 'rs.svg',
	},
	{
		code: 'RU',
		name: 'Russia',
		calling_code: 7,
		flag_class: 'fi fi-ru',
		flag: 'ru.svg',
	},
	{
		code: 'RW',
		name: 'Rwanda',
		calling_code: 250,
		flag_class: 'fi fi-rw',
		flag: 'rw.svg',
	},
	{
		code: 'SA',
		name: 'Saudi Arabia',
		calling_code: 966,
		flag_class: 'fi fi-sa',
		flag: 'sa.svg',
	},
	{
		code: 'SB',
		name: 'Solomon Islands',
		calling_code: 677,
		flag_class: 'fi fi-sb',
		flag: 'sb.svg',
	},
	{
		code: 'SC',
		name: 'Seychelles',
		calling_code: 248,
		flag_class: 'fi fi-sc',
		flag: 'sc.svg',
	},
	{
		code: 'SD',
		name: 'Sudan',
		calling_code: 249,
		flag_class: 'fi fi-sd',
		flag: 'sd.svg',
	},
	{
		code: 'SE',
		name: 'Sweden',
		calling_code: 46,
		flag_class: 'fi fi-se',
		flag: 'se.svg',
	},
	{
		code: 'SG',
		name: 'Singapore',
		calling_code: 65,
		flag_class: 'fi fi-sg',
		flag: 'sg.svg',
	},
	{
		code: 'SH',
		name: 'Saint Helena, Ascension and Tristan da Cunha',
		calling_code: 290,
		flag_class: 'fi fi-sh',
		flag: 'sh.svg',
	},
	{
		code: 'SI',
		name: 'Slovenia',
		calling_code: 386,
		flag_class: 'fi fi-si',
		flag: 'si.svg',
	},
	{
		code: 'SJ',
		name: 'Svalbard and Jan Mayen',
		calling_code: 47,
		flag_class: 'fi fi-sj',
		flag: 'sj.svg',
	},
	{
		code: 'SK',
		name: 'Slovakia',
		calling_code: 421,
		flag_class: 'fi fi-sk',
		flag: 'sk.svg',
	},
	{
		code: 'SL',
		name: 'Sierra Leone',
		calling_code: 232,
		flag_class: 'fi fi-sl',
		flag: 'sl.svg',
	},
	{
		code: 'SM',
		name: 'San Marino',
		calling_code: 378,
		flag_class: 'fi fi-sm',
		flag: 'sm.svg',
	},
	{
		code: 'SN',
		name: 'Senegal',
		calling_code: 221,
		flag_class: 'fi fi-sn',
		flag: 'sn.svg',
	},
	{
		code: 'SO',
		name: 'Somalia',
		calling_code: 252,
		flag_class: 'fi fi-so',
		flag: 'so.svg',
	},
	{
		code: 'SR',
		name: 'Suriname',
		calling_code: 597,
		flag_class: 'fi fi-sr',
		flag: 'sr.svg',
	},
	{
		code: 'SS',
		name: 'South Sudan',
		calling_code: 211,
		flag_class: 'fi fi-ss',
		flag: 'ss.svg',
	},
	{
		code: 'ST',
		name: 'São Tomé and Príncipe',
		calling_code: 239,
		flag_class: 'fi fi-st',
		flag: 'st.svg',
	},
	{
		code: 'SV',
		name: 'El Salvador',
		calling_code: 503,
		flag_class: 'fi fi-sv',
		flag: 'sv.svg',
	},
	{
		code: 'SX',
		name: 'Sint Maarten',
		calling_code: 1,
		flag_class: 'fi fi-sx',
		flag: 'sx.svg',
	},
	{
		code: 'SY',
		name: 'Syria',
		calling_code: 963,
		flag_class: 'fi fi-sy',
		flag: 'sy.svg',
	},
	{
		code: 'SZ',
		name: 'Eswatini',
		calling_code: 268,
		flag_class: 'fi fi-sz',
		flag: 'sz.svg',
	},
	{
		code: 'TA',
		name: 'TA',
		calling_code: 290,
		flag_class: 'fi fi-ta',
		flag: 'ta.svg',
	},
	{
		code: 'TC',
		name: 'Turks and Caicos Islands',
		calling_code: 1,
		flag_class: 'fi fi-tc',
		flag: 'tc.svg',
	},
	{
		code: 'TD',
		name: 'Chad',
		calling_code: 235,
		flag_class: 'fi fi-td',
		flag: 'td.svg',
	},
	{
		code: 'TG',
		name: 'Togo',
		calling_code: 228,
		flag_class: 'fi fi-tg',
		flag: 'tg.svg',
	},
	{
		code: 'TH',
		name: 'Thailand',
		calling_code: 66,
		flag_class: 'fi fi-th',
		flag: 'th.svg',
	},
	{
		code: 'TJ',
		name: 'Tajikistan',
		calling_code: 992,
		flag_class: 'fi fi-tj',
		flag: 'tj.svg',
	},
	{
		code: 'TK',
		name: 'Tokelau',
		calling_code: 690,
		flag_class: 'fi fi-tk',
		flag: 'tk.svg',
	},
	{
		code: 'TL',
		name: 'Timor-Leste',
		calling_code: 670,
		flag_class: 'fi fi-tl',
		flag: 'tl.svg',
	},
	{
		code: 'TM',
		name: 'Turkmenistan',
		calling_code: 993,
		flag_class: 'fi fi-tm',
		flag: 'tm.svg',
	},
	{
		code: 'TN',
		name: 'Tunisia',
		calling_code: 216,
		flag_class: 'fi fi-tn',
		flag: 'tn.svg',
	},
	{
		code: 'TO',
		name: 'Tonga',
		calling_code: 676,
		flag_class: 'fi fi-to',
		flag: 'to.svg',
	},
	{
		code: 'TR',
		name: 'Turkey',
		calling_code: 90,
		flag_class: 'fi fi-tr',
		flag: 'tr.svg',
	},
	{
		code: 'TT',
		name: 'Trinidad and Tobago',
		calling_code: 1,
		flag_class: 'fi fi-tt',
		flag: 'tt.svg',
	},
	{
		code: 'TV',
		name: 'Tuvalu',
		calling_code: 688,
		flag_class: 'fi fi-tv',
		flag: 'tv.svg',
	},
	{
		code: 'TW',
		name: 'Taiwan',
		calling_code: 886,
		flag_class: 'fi fi-tw',
		flag: 'tw.svg',
	},
	{
		code: 'TZ',
		name: 'Tanzania',
		calling_code: 255,
		flag_class: 'fi fi-tz',
		flag: 'tz.svg',
	},
	{
		code: 'UA',
		name: 'Ukraine',
		calling_code: 380,
		flag_class: 'fi fi-ua',
		flag: 'ua.svg',
	},
	{
		code: 'UG',
		name: 'Uganda',
		calling_code: 256,
		flag_class: 'fi fi-ug',
		flag: 'ug.svg',
	},
	{
		code: 'US',
		name: 'United States',
		calling_code: 1,
		flag_class: 'fi fi-us',
		flag: 'us.svg',
	},
	{
		code: 'UY',
		name: 'Uruguay',
		calling_code: 598,
		flag_class: 'fi fi-uy',
		flag: 'uy.svg',
	},
	{
		code: 'UZ',
		name: 'Uzbekistan',
		calling_code: 998,
		flag_class: 'fi fi-uz',
		flag: 'uz.svg',
	},
	{
		code: 'VA',
		name: 'Vatican City',
		calling_code: 39,
		flag_class: 'fi fi-va',
		flag: 'va.svg',
	},
	{
		code: 'VC',
		name: 'Saint Vincent and the Grenadines',
		calling_code: 1,
		flag_class: 'fi fi-vc',
		flag: 'vc.svg',
	},
	{
		code: 'VE',
		name: 'Venezuela',
		calling_code: 58,
		flag_class: 'fi fi-ve',
		flag: 've.svg',
	},
	{
		code: 'VG',
		name: 'British Virgin Islands',
		calling_code: 1,
		flag_class: 'fi fi-vg',
		flag: 'vg.svg',
	},
	{
		code: 'VI',
		name: 'United States Virgin Islands',
		calling_code: 1,
		flag_class: 'fi fi-vi',
		flag: 'vi.svg',
	},
	{
		code: 'VN',
		name: 'Vietnam',
		calling_code: 84,
		flag_class: 'fi fi-vn',
		flag: 'vn.svg',
	},
	{
		code: 'VU',
		name: 'Vanuatu',
		calling_code: 678,
		flag_class: 'fi fi-vu',
		flag: 'vu.svg',
	},
	{
		code: 'WF',
		name: 'Wallis and Futuna',
		calling_code: 681,
		flag_class: 'fi fi-wf',
		flag: 'wf.svg',
	},
	{
		code: 'WS',
		name: 'Samoa',
		calling_code: 685,
		flag_class: 'fi fi-ws',
		flag: 'ws.svg',
	},
	{
		code: 'XK',
		name: 'Kosovo',
		calling_code: 383,
		flag_class: 'fi fi-xk',
		flag: 'xk.svg',
	},
	{
		code: 'YE',
		name: 'Yemen',
		calling_code: 967,
		flag_class: 'fi fi-ye',
		flag: 'ye.svg',
	},
	{
		code: 'YT',
		name: 'Mayotte',
		calling_code: 262,
		flag_class: 'fi fi-yt',
		flag: 'yt.svg',
	},
	{
		code: 'ZA',
		name: 'South Africa',
		calling_code: 27,
		flag_class: 'fi fi-za',
		flag: 'za.svg',
	},
	{
		code: 'ZM',
		name: 'Zambia',
		calling_code: 260,
		flag_class: 'fi fi-zm',
		flag: 'zm.svg',
	},
	{
		code: 'ZW',
		name: 'Zimbabwe',
		calling_code: 263,
		flag_class: 'fi fi-zw',
		flag: 'zw.svg',
	},
];
